# Generated by Django 5.2.10 on 2026-04-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Analyst'), ('user', 'Viewer')], default='user', max_length=10),
        ),
    ]
